# Generated by Django 5.1.2 on 2024-11-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_product_order_product_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order',
            new_name='orders',
        ),
        migrations.AlterField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
