# Generated by Django 5.1.2 on 2024-11-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_order_cart_orders_alter_cart_ordered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='orderAccepted',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
