# Generated by Django 5.1.2 on 2024-11-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_order_date_order_orderdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivered',
            new_name='OrderDelivered',
        ),
    ]
