# Generated by Django 5.1.2 on 2024-11-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_delivered_order_orderdelivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='OrderDelivered',
            new_name='orderDelivered',
        ),
        migrations.AddField(
            model_name='order',
            name='orderNoteAccept',
            field=models.BooleanField(default=False),
        ),
    ]
