# Generated by Django 5.1.2 on 2024-11-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_orderpackaging'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderNoteAccept',
            new_name='orderAborted',
        ),
    ]
