# Generated by Django 5.1.2 on 2024-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_ordernoteaccept_order_orderaborted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderAborted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderDate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderDelivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderPackaging',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('pre_order', 'Pre Order')], default='', max_length=50),
        ),
    ]
