# Generated by Django 5.1.2 on 2024-11-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_order_orderaborted_remove_order_orderdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderAccepted',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(choices=[('value_1', 1), ('value_2', 2), ('value_3', 3), ('value_4', 4), ('value_5', 5)], default=0),
        ),
    ]
