# Generated by Django 5.1.2 on 2024-11-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_order_orderaccepted_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Order Accepted'), (2, 'Order Aborted'), (3, 'Order Packaged'), (4, 'Order Delivered')], default='', max_length=1),
        ),
    ]
