# Generated by Django 5.1.2 on 2024-11-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Rated 1'), (2, 'Rated 2'), (3, 'Rated 3'), (4, 'Rated 4'), (5, 'Rated 5')], default=0),
        ),
    ]
